# Generated by Django 6.0 on 2025-12-07 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gender', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='first_name', max_length=250)),
                ('surname', models.CharField(db_column='last_name', max_length=250)),
                ('birth_day', models.IntegerField(db_column='birth_day')),
                ('birth_month', models.IntegerField(db_column='birth_month')),
                ('birth_year', models.IntegerField(db_column='birth_year')),
                ('email', models.CharField(db_column='eMail', max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('updateddate', models.DateTimeField(blank=True, db_column='update_date', null=True)),
                ('gender', models.ForeignKey(db_column='gender', on_delete=django.db.models.deletion.DO_NOTHING, to='gender.gender')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': 'Kullanıcıların Bilgisi',
            },
        ),
    ]
