# Generated by Django 6.0 on 2025-12-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('createddate', models.DateTimeField(db_column='create_date')),
                ('updateddate', models.DateTimeField(blank=True, db_column='update_date', null=True)),
            ],
            options={
                'db_table': 'gender',
                'db_table_comment': 'Cinsiyet Bilgileri',
            },
        ),
    ]
