# Generated by Django 6.0 on 2025-12-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cookingareatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeType',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_type',
                'db_table_comment': 'zaman birimi',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cookingareatype',
            options={'managed': True},
        ),
    ]
