# Generated by Django 6.0 on 2025-12-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('recipe', models.TextField()),
                ('cooking_time', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipes',
                'db_table_comment': 'Yemek tarifi',
                'managed': False,
            },
        ),
    ]
