# Generated by Django 6.0 on 2025-12-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favoriterecipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgePhotos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fridge_photos',
                'db_table_comment': 'buzdolabı fotoğ\xadrafı',
                'managed': False,
            },
        ),
    ]
