# Generated by Django 6.0 on 2025-12-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fridgephotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealHistories',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cooked_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meal_histories',
                'db_table_comment': 'Yemek geçmişi',
                'managed': False,
            },
        ),
    ]
