# Generated by Django 6.0 on 2025-12-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mealhistories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('unit', models.IntegerField()),
            ],
            options={
                'db_table': 'recipe_ingredients',
                'db_table_comment': 'yemek malzeme ilişkisi',
                'managed': False,
            },
        ),
    ]
